services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - FAST_REFRESH=true
      - WATCHPACK_POLLING=true
      - REACT_APP_ENV=development
    stdin_open: true # For interactive sessions
    tty: true # For interactive sessions
    restart: always
    # Use host networking for better WebSocket performance (Linux only)
    # network_mode: "host" # Uncomment this on Linux hosts for better performance
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 