# Generated by Django 4.2.7 on 2025-02-28 18:30

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='gat_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='General Aptitude Test score in percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='high_school_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='High School Grade Point Average in percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='saath_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Scholastic Achievement Test score in percentage', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
