# Generated by Django 4.0.10 on 2025-03-16 00:14

from django.db import migrations


def set_existing_users_as_verified(apps, schema_editor):
    """Set all existing users as verified."""
    User = apps.get_model('users', 'User')
    User.objects.all().update(is_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_verified'),
    ]

    operations = [
        migrations.RunPython(set_existing_users_as_verified),
    ]
